### ISSUE TITLE
More details?

### ISSUE THREAD

**Issue by mattbk** [headquarters/change-blindness#1]
Hey, I'm interested in using this, but I'm not sure how to install and run it.  Any help you could provide in the readme?

**Comment by headquarters** [comment]
Hey, sorry for being so lax about maintaining this repo that I just now saw this. I'll try to get the README updated sometime soon, even though I bet it's a bit too late to be useful now. ;)

**Comment by mattbk** [comment]
It might still be useful. I'm more of a PHP guy so I've been playing with https://github.com/mattbk/changeblindness off an on, but if I had a few hints this might end up working better for me. No worries either way.

**Comment by headquarters** [comment]
I updated the README, but feel free to re-open this issue and/or post questions if you have more specific things you'd like to see there.
